Trial : Launch Page
grasshopperfund/grasshopperfund pull request #81
Opened 2020-12-02 12:27 UTC by Amarysti

**Changes made:**
1. users/home_page.html
2. main.html

**Details:**
1. home_page.html 

- **_including :_** HTML (between content block) + CSS (between content block) + JavaScript (at the very bottom)
- add side navbar ( navbar is fixed) -> **source** : https://www.techwithtim.net/tutorials/django/adding-a-sidebar/
- add headings cards (introduction to grasshopper fund) -> **source**: materialize.css  
- add featured campaigns slider (without progress bar and the next & prev icons) -> **source**: materialize.css from section JavaScript/Media/Slider
- add organization cards + progress bar -> **source**: materialize.css and https://www.w3schools.com/w3css/w3css_progressbar.asp

2. main.html
- Ensure that when user scroll down a page, the nav bar won't move and would follow them throughout the scrolling.
- add style.css on navigation bar to code the  <style type="text/css">

```
  .nav-wrapper{
        z-index:1400;
        position: fixed;
      }
    
    </style>

```

2020-12-03 16:50 UTC, nananananate requested changes
I'll pull down this branch to remove `.vscode` and `node_modules` files.

2020-12-03 17:07 UTC, nananananate approved these changes

2020-12-03 17:08 UTC, nananananate approved these changes

2020-12-03 21:52 UTC, ovyab reviewed
homepage looks great. however i'm not sure if the main.html version you used was up-to-date with the one in dev - let's discuss more in meeting

2020-12-04 02:47 UTC, nananananate commented
@Amarysti As said in the meeting, the easiest approach to resolve the merge conflicts is to create a new branch that **branches from `dev`**. Please give that branch a name that is appropriate for your feature, thanks!

Let me know if you need any help, I'm always down to walk you through it.

2020-12-05 00:30 UTC, closed without merging